### ISSUE TITLE
Error when building with gcc

### ISSUE THREAD

**Issue by Luminiscental** [saivert/ddb_misc_headerbar_GTK3#19] opened 2024-05-16 10:58 UTC
I cloned master, built using the arch PKGBUILD, and encountered this error:
```
headerbarui.c: In function ‘window_init_hook’:
headerbarui.c:1186:31: error: passing argument 1 of ‘action_shuffle_mode_init’ from incompatible pointer type [-Wincompatible-pointer-types]
 1186 |     action_shuffle_mode_init (g_action_map_lookup_action (G_ACTION_MAP (group), "shufflemode"));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               |
      |                               GAction * {aka struct _GAction *}
headerbarui.c:484:41: note: expected ‘GSimpleAction *’ {aka ‘struct _GSimpleAction *’} but argument is of type ‘GAction *’ {aka ‘struct _GAction *’}
  484 | action_shuffle_mode_init(GSimpleAction *action)
      |                          ~~~~~~~~~~~~~~~^~~~~~
headerbarui.c:1191:30: error: passing argument 1 of ‘action_repeat_mode_init’ from incompatible pointer type [-Wincompatible-pointer-types]
 1191 |     action_repeat_mode_init (g_action_map_lookup_action (G_ACTION_MAP (group), "repeatmode"));
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              |
      |                              GAction * {aka struct _GAction *}
headerbarui.c:556:40: note: expected ‘GSimpleAction *’ {aka ‘struct _GSimpleAction *’} but argument is of type ‘GAction *’ {aka ‘struct _GAction *’}
  556 | action_repeat_mode_init(GSimpleAction *action)
      |                         ~~~~~~~~~~~~~~~^~~~~~
```
Full build output: [log.txt](https://github.com/saivert/ddb_misc_headerbar_GTK3/files/15333990/log.txt)

**Comment by dreirund** [comment] 2024-05-17 12:48
@Luminiscental, can you make your bug report more specific?

I have the same issue, I would title it like "*Fails to build with ``headerbarui.c:1186:31: error: passing argument 1 of ‘action_shuffle_mode_init’ from incompatible pointer type [-Wincompatible-pointer-types]``, GCC 14.1.1*"

(I am on GCC 14.1.1.)

Adding ` -Wno-error=incompatible-pointer-types` to `CFLAGS` and `CXXFLAGS` environment variables does workaround this. But in the root cause, the sources need to be fixed.

**Comment by saivert** [comment] 2024-05-17 12:58
Yes gcc now has stricter checks. I will fix later.

**Comment by saivert** [comment] 2024-05-18 11:36
Fixed now.

**Closed as completed by saivert** 2024-05-18 11:36 UTC
